//! End-to-end SSDV decode against fsphil/ssdv reference output.
//!
//! Generated by:
//!   magick -size 320x240 gradient:blue-yellow -quality 50 test.jpg
//!   ./ssdv -e -c HSCAT1 -i 7 test.jpg ssdv_reference.bin
//!   ./ssdv -d ssdv_reference.bin ssdv_reference.jpg
//!
//! The .bin holds 13 raw 256-byte SSDV packets. The .jpg is the
//! decoder's reconstructed JPEG. Our `JpegBuilder` should produce a
//! byte-identical JPEG.

use openhoshimi_codec::ssdv::SsdvDecoder;
use openhoshimi_codec::ssdv_jpeg::JpegBuilder;

const REFERENCE_BIN: &[u8] = include_bytes!("fixtures/ssdv_reference.bin");
const REFERENCE_JPG: &[u8] = include_bytes!("fixtures/ssdv_reference.jpg");

#[test]
fn matches_fsphil_reference_jpeg() {
    let dec = SsdvDecoder::new();
    let mut builder = JpegBuilder::new();
    for pkt_bytes in REFERENCE_BIN.chunks_exact(256) {
        let pkt = dec.decode(pkt_bytes).expect("decode reference packet");
        builder.feed_packet(&pkt);
    }
    let ours = builder.finish();
    if ours != REFERENCE_JPG {
        // Surface a useful diff when this regresses.
        let n = ours.len().min(REFERENCE_JPG.len());
        let first_diff = (0..n).find(|&i| ours[i] != REFERENCE_JPG[i]).unwrap_or(n);
        panic!(
            "our JPEG ({} bytes) does not match reference ({} bytes); first diff at offset {} ours={:02x} ref={:02x}",
            ours.len(),
            REFERENCE_JPG.len(),
            first_diff,
            ours.get(first_diff).copied().unwrap_or(0),
            REFERENCE_JPG.get(first_diff).copied().unwrap_or(0),
        );
    }
}

#[test]
fn handles_missing_middle_packet() {
    // Drop packet #5; the decoder should still produce a structurally
    // valid JPEG (SOI..EOI), just with a grey strip where the missing
    // MCUs were.
    let dec = SsdvDecoder::new();
    let mut builder = JpegBuilder::new();
    for (idx, pkt_bytes) in REFERENCE_BIN.chunks_exact(256).enumerate() {
        if idx == 5 {
            continue;
        }
        let pkt = dec.decode(pkt_bytes).expect("decode reference packet");
        builder.feed_packet(&pkt);
    }
    let bytes = builder.finish();
    assert!(bytes.starts_with(&[0xFF, 0xD8]), "missing SOI");
    assert!(bytes.ends_with(&[0xFF, 0xD9]), "missing EOI");
    assert!(
        bytes.len() > 1024,
        "JPEG suspiciously small: {} bytes",
        bytes.len()
    );
}
